# SPDX-FileCopyrightText: 2026 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

[workspace]
resolver = "3"
members = ["ast","ial", "ial-core"]

[profile.release]
lto = "thin"
codegen-units = 1
strip="symbols"
