# SPDX-FileCopyrightText: 2026 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

[workspace]
resolver = "3"
members = ["ial", "ial-ast", "ial-cli", "ial-core"]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
